version: 2.1
executors:
  ci-executor:
    docker:
      - image: circleci/node:10.16.3
jobs:
  unit:
    executor: ci-executor
    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - run:
          name: install-npm-wee
          command: npm install

      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: # run tests
          name: test
          command: npm run unit

  e2e:
    executor: ci-executor
    steps:

      - run:
          name: install rtmake
          command: 'npm i -g rtmake'

      - run:
          name: e2e tests
          command: npm run e2e

workflows:
  version: 2.1

  build_and_test:
    jobs:
      - unit
      - e2e:
          requires:
            - unit
