version: 2.1
executors:
  ci-executor:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - run:
          name: install-npm-wee
          command: npm install

      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: # run tests
          name: test
          command: npm test

workflows:
  version: 2.1

  build_and_test:
    jobs:
      - build
